In [1]:
import pandas as pd

In [2]:
aylik_harcama = pd.Series(
    data=[3200, 2800, 4100, 3750, 5200,4800, 
     6100, 5900, 4400, 3600, 5100, 7200],
    index=['Ocak', 'Şubat', 'Mart', 'Nisan','Mayıs', 'Haziran', 
           'Temmuz', 'Ağustos', 'Eylül', 'Ekim', 'Kasım', 'Aralık'])

In [3]:
aylik_harcama

Ocak       3200
Şubat      2800
Mart       4100
Nisan      3750
Mayıs      5200
Haziran    4800
Temmuz     6100
Ağustos    5900
Eylül      4400
Ekim       3600
Kasım      5100
Aralık     7200
dtype: int64

In [4]:
aylik_harcama.values

array([3200, 2800, 4100, 3750, 5200, 4800, 6100, 5900, 4400, 3600, 5100,
       7200])

In [5]:
aylik_harcama.index

Index(['Ocak', 'Şubat', 'Mart', 'Nisan', 'Mayıs', 'Haziran', 'Temmuz',
       'Ağustos', 'Eylül', 'Ekim', 'Kasım', 'Aralık'],
      dtype='object')

In [6]:
aylik_harcama.dtype

dtype('int64')

In [7]:
aylik_harcama.mean()

np.float64(4679.166666666667)

In [8]:
data = {
    'CustomerName':   ['Ahmet', 'Zeynep', 'Mehmet', 'Ayşe',
                          'Can', 'Fatma', 'Burak', 'Elif'],
    'City':            ['İstanbul', 'Ankara', 'İstanbul', 'İzmir',
                          'Ankara', 'İstanbul', 'İzmir', 'İstanbul'],
    'MonthlySpending': [7200, 5400, 9200, 4300,
                          6100, 8800, 3900, 5700],
    'MembershipType': ['Gold', 'Silver', 'Platinum', 'Silver',
                          'Gold', 'Platinum', 'Silver', 'Gold']
}

In [9]:
dataFrame = pd.DataFrame(data)

In [10]:
dataFrame

  CustomerName      City  MonthlySpending MembershipType
0        Ahmet  İstanbul             7200           Gold
1       Zeynep    Ankara             5400         Silver
2       Mehmet  İstanbul             9200       Platinum
3         Ayşe     İzmir             4300         Silver
4          Can    Ankara             6100           Gold
5        Fatma  İstanbul             8800       Platinum
6        Burak     İzmir             3900         Silver
7         Elif  İstanbul             5700           Gold

In [13]:
dataFrame.set_index("CustomerName", inplace = True)

In [14]:
dataFrame.loc["Zeynep"]

City               Ankara
MonthlySpending      5400
MembershipType     Silver
Name: Zeynep, dtype: object

In [18]:
dataFrame.reset_index(inplace = True)

In [19]:
dataFrame.set_index("MembershipType")

               CustomerName      City  MonthlySpending
MembershipType
Gold                  Ahmet  İstanbul             7200
Silver               Zeynep    Ankara             5400
Platinum             Mehmet  İstanbul             9200
Silver                 Ayşe     İzmir             4300
Gold                    Can    Ankara             6100
Platinum              Fatma  İstanbul             8800
Silver                Burak     İzmir             3900
Gold                   Elif  İstanbul             5700

In [20]:
dataFrame

  CustomerName      City  MonthlySpending MembershipType
0        Ahmet  İstanbul             7200           Gold
1       Zeynep    Ankara             5400         Silver
2       Mehmet  İstanbul             9200       Platinum
3         Ayşe     İzmir             4300         Silver
4          Can    Ankara             6100           Gold
5        Fatma  İstanbul             8800       Platinum
6        Burak     İzmir             3900         Silver
7         Elif  İstanbul             5700           Gold

In [21]:
multiFrame = dataFrame.set_index(["City","MembershipType"])

In [22]:
multiFrame

                        CustomerName  MonthlySpending
City     MembershipType
İstanbul Gold                  Ahmet             7200
Ankara   Silver               Zeynep             5400
İstanbul Platinum             Mehmet             9200
İzmir    Silver                 Ayşe             4300
Ankara   Gold                    Can             6100
İstanbul Platinum              Fatma             8800
İzmir    Silver                Burak             3900
İstanbul Gold                   Elif             5700

In [25]:
multiFrame.loc["İstanbul"].loc["Gold"]

               CustomerName  MonthlySpending
MembershipType
Gold                  Ahmet             7200
Gold                   Elif             5700

In [30]:
dataFrame

  CustomerName      City  MonthlySpending MembershipType
0        Ahmet  İstanbul             7200           Gold
1       Zeynep    Ankara             5400         Silver
2       Mehmet  İstanbul             9200       Platinum
3         Ayşe     İzmir             4300         Silver
4          Can    Ankara             6100           Gold
5        Fatma  İstanbul             8800       Platinum
6        Burak     İzmir             3900         Silver
7         Elif  İstanbul             5700           Gold

In [31]:
print(f"Toplam müşteri sayısı: {len(dataFrame)}")
print(f"En yüksek aylık harcama: {dataFrame["MonthlySpending"].max()}")
print(f"En çok müşteri olan şehir: {dataFrame["City"].value_counts().idxmax()}")

Toplam müşteri sayısı: 8
En yüksek aylık harcama: 9200
En çok müşteri olan şehir: İstanbul