In [1]:
import pandas as pd
import numpy as np

In [2]:
customers = {
    "CustomerID" : [1,2,3,4],
    "CustomerName" : ["Furkan","Berkay","Beyza","Selin"],
    "City" : ["Samsun","Ankara","Denizli","Muğla"],
    "Age" : [23,np.nan,21,np.nan]
}

In [3]:
customerDF = pd.DataFrame(customers)

In [4]:
customerDF

   CustomerID CustomerName     City   Age
0           1       Furkan   Samsun  23.0
1           2       Berkay   Ankara   NaN
2           3        Beyza  Denizli  21.0
3           4        Selin    Muğla   NaN

In [5]:
sales = {
    "SaleID" : [2,1,4,5],
    "CustomerID" : [1,2,3,4],
    "Product" : ["Bilgisayar","Telefon","Kulaklık","Bilgisayar"],
    "Amount" : [30000,25000,np.nan,np.nan]
}

In [6]:
salesDF = pd.DataFrame(sales)

In [7]:
salesDF

   SaleID  CustomerID     Product   Amount
0       2           1  Bilgisayar  30000.0
1       1           2     Telefon  25000.0
2       4           3    Kulaklık      NaN
3       5           4  Bilgisayar      NaN

In [8]:
regions = {
    "City" : ["Samsun","Denizli","Ankara","Muğla"],
    "Region" : ["Karadeniz","Ege","İç Anadolu","Ege"]
}

In [9]:
regionsDF = pd.DataFrame(regions)

In [10]:
regionsDF

      City      Region
0   Samsun   Karadeniz
1  Denizli         Ege
2   Ankara  İç Anadolu
3    Muğla         Ege

In [11]:
# eksik değerlerin tespiti

In [12]:
customerDF.isnull()

   CustomerID  CustomerName   City    Age
0       False         False  False  False
1       False         False  False   True
2       False         False  False  False
3       False         False  False   True

In [13]:
# Yaş için ortalama ile doldur

In [14]:
customerDF["Age"] = customerDF["Age"].fillna(customerDF["Age"].mean())

In [15]:
customerDF

   CustomerID CustomerName     City   Age
0           1       Furkan   Samsun  23.0
1           2       Berkay   Ankara  22.0
2           3        Beyza  Denizli  21.0
3           4        Selin    Muğla  22.0

In [16]:
# satış tutarı eksik olan kayıtları sil

In [17]:
salesDF

   SaleID  CustomerID     Product   Amount
0       2           1  Bilgisayar  30000.0
1       1           2     Telefon  25000.0
2       4           3    Kulaklık      NaN
3       5           4  Bilgisayar      NaN

In [18]:
salesDF = salesDF.dropna(subset=["Amount"])

In [19]:
salesDF

   SaleID  CustomerID     Product   Amount
0       2           1  Bilgisayar  30000.0
1       1           2     Telefon  25000.0

In [20]:
# merge
# customers + sales → CustomerID üzerinden birleştir

In [21]:
mergedDF = pd.merge(customerDF,salesDF, on="CustomerID")

In [22]:
mergedDF

   CustomerID CustomerName    City   Age  SaleID     Product   Amount
0           1       Furkan  Samsun  23.0       2  Bilgisayar  30000.0
1           2       Berkay  Ankara  22.0       1     Telefon  25000.0

In [23]:
# regions ile birleştirme

In [24]:
sonMergedDF = pd.merge(mergedDF, regionsDF)

In [25]:
sonMergedDF

,CustomerID,CustomerName,City,Age,SaleID,Product,Amount,Region
0,1,Furkan,Samsun,23.0,2,Bilgisayar,30000.0,Karadeniz
1,2,Berkay,Ankara,22.0,1,Telefon,25000.0,İç Anadolu

In [26]:
# group by şehir bazlı

In [27]:
groupSehir = sonMergedDF.groupby("City" ).agg(["sum"])

In [28]:
groupSehir

       CustomerID CustomerName   Age SaleID     Product   Amount      Region
              sum          sum   sum    sum         sum      sum         sum
City
Ankara          2       Berkay  22.0      1     Telefon  25000.0  İç Anadolu
Samsun          1       Furkan  23.0      2  Bilgisayar  30000.0   Karadeniz

In [29]:
# group by bölge bazlı ort satış

In [30]:
groupBolge = sonMergedDF.groupby("Region").agg({"Amount": "mean"})

In [31]:
groupBolge

             Amount
Region
Karadeniz   30000.0
İç Anadolu  25000.0

In [32]:
# ürün bazlı satış sayısı

In [33]:
groupUrun = sonMergedDF.groupby("Product").agg(["count"])

In [34]:
groupUrun

           CustomerID CustomerName  City   Age SaleID Amount Region
                count        count count count  count  count  count
Product
Bilgisayar          1            1     1     1      1      1      1
Telefon             1            1     1     1      1      1      1

In [35]:
# concat
# farklı aylara ait iki satış tablosu oluşturma

In [36]:
ocak = pd.DataFrame({
    "SaleID": [1, 2, 3],
    "Product": ["Bilgisayar", "Telefon", "Kulaklık"],
    "Amount": [30000, 25000, 1500],
    "Month": ["Ocak", "Ocak", "Ocak"]
})

In [37]:
ocak

   SaleID     Product  Amount Month
0       1  Bilgisayar   30000  Ocak
1       2     Telefon   25000  Ocak
2       3    Kulaklık    1500  Ocak

In [38]:
subat = pd.DataFrame({
    "SaleID": [4, 5, 6],
    "Product": ["Bilgisayar", "Telefon", "Kulaklık"],
    "Amount": [32000, 27000, 2000],
    "Month": ["Şubat", "Şubat", "Şubat"]
})

In [39]:
subat

   SaleID     Product  Amount  Month
0       4  Bilgisayar   32000  Şubat
1       5     Telefon   27000  Şubat
2       6    Kulaklık    2000  Şubat

In [59]:
# satır bazlı birleştirme

In [60]:
satislar = pd.concat([ocak, subat], axis=0)

In [61]:
satislar

   SaleID     Product  Amount  Month
0       1  Bilgisayar   30000   Ocak
1       2     Telefon   25000   Ocak
2       3    Kulaklık    1500   Ocak
0       4  Bilgisayar   32000  Şubat
1       5     Telefon   27000  Şubat
2       6    Kulaklık    2000  Şubat

In [62]:
# koşullu filtreleme

In [63]:
booleanFrame = satislar["Amount"] > 20000

In [64]:
satislar[booleanFrame]

   SaleID     Product  Amount  Month
0       1  Bilgisayar   30000   Ocak
1       2     Telefon   25000   Ocak
0       4  Bilgisayar   32000  Şubat
1       5     Telefon   27000  Şubat

In [65]:
# yeni sütun oluşturma

In [66]:
satislar["KDVli Satış"] = satislar["Amount"] * 1.5

In [67]:
satislar

   SaleID     Product  Amount  Month  KDVli Satış
0       1  Bilgisayar   30000   Ocak      45000.0
1       2     Telefon   25000   Ocak      37500.0
2       3    Kulaklık    1500   Ocak       2250.0
0       4  Bilgisayar   32000  Şubat      48000.0
1       5     Telefon   27000  Şubat      40500.0
2       6    Kulaklık    2000  Şubat       3000.0

In [68]:
# apply kullanımı

In [69]:
print(satislar['Amount'].dtype)

int64

In [70]:
def new_amount(deger):
    return int(deger) + 2500

In [71]:
satislar['Amount'] = satislar['Amount'].apply(new_amount)

In [72]:
satislar

   SaleID     Product  Amount  Month  KDVli Satış
0       1  Bilgisayar   32500   Ocak      45000.0
1       2     Telefon   27500   Ocak      37500.0
2       3    Kulaklık    4000   Ocak       2250.0
0       4  Bilgisayar   34500  Şubat      48000.0
1       5     Telefon   29500  Şubat      40500.0
2       6    Kulaklık    4500  Şubat       3000.0

In [73]:
# excel e yazma

In [75]:
satislar.to_excel("final_sales_report.xlsx")

In [ ]:
# çıktılar

In [84]:
# 'Amount' sütunundaki en büyük değerin olduğu satırı bul ve o satırın 'Product' ismini al
en_karli_urun = satislar.loc[satislar['Amount'].idxmax(), 'Product']

In [86]:
print(f"Toplam Satış: {satislar["Amount"].sum()}")
print(f"En kârlı ürün: {en_karli_urun}")

Toplam Satış: 132500
En kârlı ürün: 0    Bilgisayar
0    Bilgisayar
Name: Product, dtype: object